### ISSUE TITLE
Generate fixed using a KDF

### ISSUE THREAD

**Issue by chris-wood** [cfrg/draft-irtf-cfrg-randomness-improvements#10]
"I don’t like that the tag is up to the implementation to generate. You end up signing arbitrary data, where the signature could be reused elsewhere. Better to derive a key via a KDF and a unique but exact tag specified in the standard."

https://twitter.com/rootlabs/status/975216701468889088

**Comment by smyshsv** [comment]
tag1 must be bound to a device (or to VM). We've given several considerations, how to choose it - I am not sure that there's something we should add now.

And several considerations about tag2 are there too.
Not sure that we need even more specificity here.

**Comment by chris-wood** [comment]
Agreed. Closing for now.
