### ISSUE TITLE
Do not consume more entropy of G(x) than needed 

### ISSUE THREAD

**Issue by chris-wood** [cfrg/draft-irtf-cfrg-randomness-improvements#17]
Choose G(x) output size to be minimize of requested and PRF output size

**Comment by smyshsv** [comment]
The construction changed completely since March, 2018. We have a different construction now, consuming the length of output which is needed by Extract.
I'd propose to close this issue as "Won't fix".

**Comment by chris-wood** [comment]
This is fixed with #45.
