### ISSUE TITLE
Conduct experiments with existing implementations

### ISSUE THREAD

**Issue by chris-wood** [cfrg/draft-irtf-cfrg-randomness-improvements#22]

**Comment by smyshsv** [comment]
Important experiments have been conducted by Chris.
Do we need new ones or should we close the issue?

It will be great to upload the results somewhere. Any ideas, where to?

**Comment by chris-wood** [comment]
@chris-wood good question. I can clean up the code and put it here.

**Comment by chris-wood** [comment]
This is done! (Details in the paper.) Closing.
