### ISSUE TITLE
Add details about the experiments conducted by Chris

### ISSUE THREAD

**Issue by smyshsv** [cfrg/draft-irtf-cfrg-randomness-improvements#35]
1) After Chris publishes the paper with the experimental results somewhere, add a reference to it in the draft.
2) Add some brief outline of the results in the paragraph about signature output caching.

**Comment by chris-wood** [comment]
We should update this text based on the paper results. (cc @cascremers)

**Comment by chris-wood** [comment]
Closing, since we cite the paper.
