### ISSUE TITLE
Sig() could actually be a MAC

### ISSUE THREAD

**Issue by kwantam** [cfrg/draft-irtf-cfrg-randomness-improvements#42]
Hi folks, thanks for the hard work on this draft! One quick comment:

It seems unnecessary to specify a dieterministic *signature* in the construction of `G'`. Wouldn't a MAC be just as good, much more efficient, and far easier to implement? (In particular, it seems to me that the existing security analysis would apply almost seamlessly to any secure MAC.)

I recognize that using a MAC may be at odds with the HSM use-case, but it seems almost certain that this draft is useful in many settings where an HSM is unavailable. Moreover, since there are effectively no interoperability concerns, it seems like generalizing to allow the more efficient construction is a strict win.

I'm happy to submit a PR clarifying this, if you'd like.

**Comment by chris-wood** [comment]
Sorry for the delay, @kwantam! A PR would be lovely. It’s not clear to me what is the right level of abstraction for this generalization. A PRF would be fine, and would work with what we have now (I think). What did you have in mind?

**Comment by kwantam** [comment]
Regarding the right level of abstraction: great question! But to answer it I'll have to go back and think again about what primitives would slot naturally into the existing security argument. I'll try to find some time to do this in the not-too-distant future.

**Comment by chris-wood** [comment]
Thanks! This is probably best as a followup document since we're past WGLC. So, no rush on the PR. :-)

**Comment by chris-wood** [comment]
Closing given the above. I think there's value in this addendum, but it seems outside the scope of this document's intent.
